# Generated by Django 2.2.4 on 2019-08-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190807_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='없음', verbose_name='설명'),
            preserve_default=False,
        ),
    ]
