# Generated by Django 2.2.4 on 2019-08-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
